### ISSUE TITLE
block by ASN name (ISP) or ASN number

### ISSUE THREAD

**Issue by frankofno** [rpthms/nft-geo-filter#16]
This is a feature request, to block all IP's of a provider (ISP). Sometimes bad requests are coming from a specific provider, so it would be great to block all their IP's based on their ASN name or number. Is there any chance to do that?

all the best

**Comment by rpthms** [comment]
Hmm, not totally convinced if this is a good idea. Besides, I'm not aware of any free service that would give me a list of all the IP blocks for a given ASN. My script is also pretty tightly bound to country codes, so mixing countries and ASNs could get a little complicated. Also, I don't have a ton of time right now to work on this script unfortunately, so the likelihood of this feature getting implemented is very low. Sorry!

Closing the issue.
