### ISSUE TITLE
SSL Cert expired on ipdeny.com

### ISSUE THREAD

**Issue by b0rZ84** [rpthms/nft-geo-filter#19]
Hi,

SSL Cert of ipdeny.com has just expired yesterday. Since then the script does not work.
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)>`

Can you please suggest a workaround until they renew their cert?

Regards,
Zsolt

**Comment by rpthms** [comment]
You could change your IP blocks provider to "ipverse.net" for the time being. Download the latest version of the script and run:

`nft-geo-filter --provider ipverse.net MC`

**Comment by b0rZ84** [comment]
> You could change your IP blocks provider to "ipverse.net" for the time being. Download the latest version of the script and run:
> 
> `nft-geo-filter --provider ipverse.net MC`

Cool. Thanks for the quick answer.

**Comment by nlvw** [comment]
@rpthms Good to know about the provider flag but there is a serious bug that accompanies this.  When nft-geo-filter fails due to the SSL cert error it blocks all outgoing and incoming traffic (despite any configuration or exceptions given).

```/bin/python3 /root/.timers/nft-geo-filter --allow --allow-established --exceptions "128.123.0.0/16" US```

The resulting broken ruleset:
![image](https://user-images.githubusercontent.com/5723368/119165997-5a7da880-ba1b-11eb-9329-dd7312fc90b7.png)

**Comment by nlvw** [comment]
Also, after inspecting ipverse.net it looks like the site is not HTTPS enabled.  This leaves it open to man-in-the-middle attacks (mainly concerned about packet injection) and other vulnerabilities that HTTP is susceptible too.

**Comment by b0rZ84** [comment]
Hi Guys,Nicholas is right and I totally forget to mention this. I was a bit confused when my colleagues called me 6am in the morning that something odd is happening. The only difference for me was besides there were no incoming traffic at all on the server, the outgoing traffic was OK. It took like 10 minutes until I figured out it's the firewall and deleted the corresponding table from nft.So yeah, it would be great to have a fix for this. :)Regards,Zsolt
-------- Eredeti üzenet --------Feladó: Nicholas Von Wolff ***@***.***> Dátum: 2021. 05. 21.  18:01  (GMT+01:00) Címzett: rpthms/nft-geo-filter ***@***.***> Másolatot kap: b0rZ84 ***@***.***>, Author ***@***.***> Tárgy: Re: [rpthms/nft-geo-filter] SSL Cert expired on ipdeny.com (#19) 
@rpthms Good to know about the provider flag but there is a serious bug that accompanies this.  When nft-geo-filter fails due to the SSL cert error it blocks all outgoing and incoming traffic (despite any configuration or exceptions given).
/bin/python3 /root/.timers/nft-geo-filter --allow --allow-established --exceptions "128.123.0.0/16" US
The resulting broken ruleset:

**Comment by rpthms** [comment]
> @rpthms Good to know about the provider flag but there is a serious bug that accompanies this. When nft-geo-filter fails due to the SSL cert error it blocks all outgoing and incoming traffic when using the 'allow' flag/logic.
> 
> `/bin/python3 /root/.timers/nft-geo-filter --allow --allow-established --exceptions "128.123.0.0/16" US`
> 
> The resulting broken ruleset:
> ![image](https://user-images.githubusercontent.com/5723368/119165997-5a7da880-ba1b-11eb-9329-dd7312fc90b7.png)

Yikes, that is definitely an issue. Looks like we also need to restore the old sets when we get the `urllib.error.URLError` exception. I'll submit a patch shortly. Thanks for letting me know @nlvw

**Comment by rpthms** [comment]
Hey @nlvw, @b0rZ84

I've made an update to the script on a separate branch. Could you download the script from here (https://raw.githubusercontent.com/rpthms/nft-geo-filter/handle_ssl_exceptions/nft-geo-filter) and check if you're still getting locked out when using the `--allow` flag?

**Comment by nlvw** [comment]
@rpthms 

That fixed the lockout issue I described.

**Comment by rpthms** [comment]
Thanks for confirming @nlvw . I've merged the change.
