### ISSUE TITLE
Allow outgoing traffic to blocked IP ranges

### ISSUE THREAD

**Issue by peeterm007** [rpthms/nft-geo-filter#5]
Hello

Thank you for your work on this application. I have a question concerning allowing outgoing traffic. Taking MC as an example, suppose I allow incoming traffic only from within MC

nft-geo-filter --allow MC

this entails that no incoming or outgoing traffic is allowed to non-MC addresses. But suppose I would still like to allow outgoing traffic to the rest of the world (ie packets originating from my machine). How can I achieve this? I tried adding 

ct state established,related accept

to the chain 'filter-chain' (assuming default names in this example), but it did not make a difference. 

Is there a way to make this work? It would be great to have an option for this in the program.

Thank you

**Comment by b0rZ84** [comment]
> Hmm, interesting. I tried running adding your rules on my system and run nft-geo-filter after that (along with adding the ct rule on the top of the filter-chain) and I was also not able to ping any of the IPs outside the filter set. I'm not exactly sure why this is happening. I will have to dig into it a bit more.

I have the same issue as @peeterm007 minimal ip filter table before geo-filter, inserted established,related as adviced but still no incoming packets when initiating connection.
By the way, your work is awesome. Looking forward for updated version.

**Comment by rpthms** [comment]
@b0rZ84 @peeterm007 I'm sorry for the lack of response on this issue. I've just been a bit busy the past few weeks. I still don't have an answer to this problem. I'll try to send a mail to the netfilter guys and see what they have to say about this. Will post an update if I find something worthwhile.

**Comment by rpthms** [comment]
Ok, figured it out. The reason the outgoing connections were not working was because connection state tracking operations happen using the priority -200 (https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains#Base_chain_priority). Since this script's filter-chain is also using the priority -200, there was no guarantee that the connection tracking would happen before the filter-chain's rule matching began (which could be the reason why outgoing connections would only work if no other table existed other than the geo-filter table). I reduced the filter-chain's priority to -190 so that conntrack operations would always happen before traversing the filter-chain rules and now everything is working the way it is supposed to.

Here's @peeterm007's firewall setup along with a geo-filter table to only allow packets from Monaco (along with the ct state rule).

```
table inet my_table {
        chain my_input {
                type filter hook input priority filter; policy drop;
                iif "lo" accept comment "Accept any localhost traffic"
                ct state invalid drop comment "Drop invalid connections"
                ct state established,related accept comment "Accept traffic originated from us"
                icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, mld-listener-query, mld-listener-report, mld-listener-done, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, ind-neighbor-solicit, ind-neighbor-advert, mld2-listener-report } accept comment "Accept ICMPv6"
                icmp type { destination-unreachable, router-advertisement, router-solicitation, time-exceeded, parameter-problem } accept comment "Accept ICMP"
                tcp dport 22 accept comment "Accept SSH on port 22"
                tcp dport { 80, 443 } accept comment "Accept HTTP (ports 80, 443)"
        }

        chain my_forward {
                type filter hook forward priority filter; policy drop;
        }

        chain my_output {
                type filter hook output priority filter; policy accept;
        }
}
table inet geo-filter {
        set filter-v4 {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 37.44.224.0/22, 80.94.96.0/20,
                             82.113.0.0/19, 87.238.104.0/21,
                             87.254.224.0/19, 88.209.64.0/18,
                             91.199.109.0/24, 176.114.96.0/20,
                             185.47.116.0/22, 185.162.120.0/22,
                             185.250.4.0/22, 188.191.136.0/21,
                             194.9.12.0/23, 195.20.192.0/23,
                             195.78.0.0/19, 213.133.72.0/21,
                             213.137.128.0/19 }
        }

        set filter-v6 {
                type ipv6_addr
                flags interval
                auto-merge
                elements = { 2a01:8fe0::/32,
                             2a07:9080::/29,
                             2a0b:8000::/29 }
        }

        chain filter-chain {
                type filter hook prerouting priority -190; policy drop;
                ct state established,related accept
                ip6 saddr { ::1, fe80::/10 } accept
                ip saddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } accept
                ip saddr @filter-v4 accept
                ip6 saddr @filter-v6 accept
        }
}

```

I can successfully ping addresses outside the filter-set.

```
$ ping 1.1.1.1 -c 4
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=59 time=9.13 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=59 time=8.46 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=59 time=9.53 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=59 time=9.35 ms

--- 1.1.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 8.455/9.114/9.527/0.406 ms
                                                                                                                                                                                             

$ ping google.com -c 4
PING google.com (216.58.196.110) 56(84) bytes of data.
64 bytes from del11s05-in-f14.1e100.net (216.58.196.110): icmp_seq=2 ttl=118 time=11.6 ms
64 bytes from maa03s19-in-f110.1e100.net (216.58.196.110): icmp_seq=3 ttl=118 time=12.3 ms
64 bytes from maa03s19-in-f110.1e100.net (216.58.196.110): icmp_seq=4 ttl=118 time=9.99 ms

--- google.com ping statistics ---
4 packets transmitted, 3 received, 25% packet loss, time 3020ms
rtt min/avg/max/mdev = 9.994/11.309/12.311/0.971 ms
```

@peeterm007 @b0rZ84 : Please download the script again and let me know if it works for you. You'll have to add the ct state rule manually for now using `nft insert rule inet geo-filter filter-chain ct state established,related accept`. I'll update the script soon so that it adds the ct state rule automatically as well.

**Comment by b0rZ84** [comment]
> 
> @peeterm007 @b0rZ84 : Please download the script again and let me know if it works for you. You'll have to add the ct state rule manually for now using `nft insert rule inet geo-filter filter-chain ct state established,related accept`. I'll update the script soon so that it adds the ct state rule automatically as well.

It's working perferctly now. Thanks for the quick fix!

**Comment by rpthms** [comment]
That's great to know! I'll add the ct state rule option to the script before closing this issue.

**Comment by rpthms** [comment]
@peeterm007 @b0rZ84 You can now add the ct state rule via the script itself by using the `--allow-established` flag.

Copying from the example section in the README.md:

* Only allow incoming packets from Monaco but still allow outgoing connections to any country\
  **Command to run**: `nft-geo-filter --allow --allow-established MC`\
  **Resulting ruleset**:
  ```
  table inet geo-filter {
        set filter-v4 {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 37.44.224.0/22, 80.94.96.0/20,
                             82.113.0.0/19, 87.238.104.0/21,
                             87.254.224.0/19, 88.209.64.0/18,
                             91.199.109.0/24, 176.114.96.0/20,
                             185.47.116.0/22, 185.162.120.0/22,
                             185.250.4.0/22, 188.191.136.0/21,
                             194.9.12.0/23, 195.20.192.0/23,
                             195.78.0.0/19, 213.133.72.0/21,
                             213.137.128.0/19 }
        }

        set filter-v6 {
                type ipv6_addr
                flags interval
                auto-merge
                elements = { 2a01:8fe0::/32,
                             2a07:9080::/29,
                             2a0b:8000::/29 }
        }

        chain filter-chain {
                type filter hook prerouting priority -190; policy drop;
                ct state established,related accept
                ip6 saddr { ::1, fe80::/10 } accept
                ip saddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } accept
                ip saddr @filter-v4 accept
                ip6 saddr @filter-v6 accept
        }
  }
  ```

Feel free to reopen the issue if you come across a bug.

**Comment by peeterm007** [comment]
Cool, it works now. Many thanks for fixing it!
