### ISSUE TITLE
 Allow  two countries with third country's some IPs  

### ISSUE THREAD

**Issue by imdrpn** [rpthms/nft-geo-filter#8]
Hello , firstly I really appropriated by your work on GEO filter . but at a time it's only taking one rule, also if I want to allow two countries IPs  suppose US, CN and only My public ip (IN)  Then how it will work ?

**Comment by rpthms** [comment]
Hi there,

To allow traffic from certain countries and your public IP, you can use the `--exceptions` flag to explicitly allow packets from your public IP through the firewall.

So, given your example. You'll need to run the following command:

```
# nft-geo-filter --allow --exceptions <YOUR_PUBLIC_IP> US CN
```

**Comment by imdrpn** [comment]
Hello , thanks a lot. I thought --exceptions flag will work only for those countries which we have mentioned in command .
